spring.application.name=PetTrackingProject

jwt.secret=very_long_and_super_secure_secret_key

spring.datasource.url=jdbc:mysql://localhost:3306/pet_tracking_db
# spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=appuser
spring.datasource.password=apppassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

aws.s3.accessKeyId=nonono
aws.s3.secretKey=nonono
aws.s3.bucketName=nonono
aws.s3.region=nonono

python.service.url=http://localhost:5001
python.service.token=my-super-secret-service-token